parameters:
    enable: true
    async: ~
    log: ~
    tasks: ~

services:
    scheduler.command.scheduled_task:
        class: Goksagun\SchedulerBundle\Command\ScheduledTaskCommand
        arguments: ["%enable%", "%async%", "%log%","%tasks%"]
        tags:
            - { name: 'console.command', command: 'scheduler:run' }