parameters:
    scheduler:
        enabled: true
        async: ~
        log: ~
        tasks: ~

services:
    scheduler.command.scheduled_task:
        class: Goksagun\SchedulerBundle\Command\ScheduledTaskCommand
        arguments: ['%scheduler%', '@doctrine.orm.entity_manager']
        calls:
            - method: setProjectDir
              arguments:
                  - '%kernel.project_dir%'
        tags:
            - { name: 'console.command', command: 'scheduler:run' }

    scheduler.command.scheduled_task_list:
        class: Goksagun\SchedulerBundle\Command\ScheduledTaskListCommand
        arguments: ['%scheduler%', '@doctrine.orm.entity_manager']
        tags:
            - { name: 'console.command', command: 'scheduler:list' }

    scheduler.command.scheduled_task_add:
        class: Goksagun\SchedulerBundle\Command\SchedulerTaskAddCommand
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: 'console.command', command: 'scheduler:add' }

    scheduler.command.scheduled_task_edit:
        class: Goksagun\SchedulerBundle\Command\SchedulerTaskEditCommand
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: 'console.command', command: 'scheduler:edit' }

    scheduler.service.scheduled_task:
        class: Goksagun\SchedulerBundle\Service\ScheduledTaskService
        arguments: ['%scheduler%', '%console.command.ids%', '@service_container', '@scheduler.repository.scheduled_task']

    scheduler.repository.scheduled_task:
        class: Goksagun\SchedulerBundle\Repository\ScheduledTaskRepository
        arguments: ['@Doctrine\Common\Persistence\ManagerRegistry']

    scheduler.repository.scheduled_task_log:
        class: Goksagun\SchedulerBundle\Repository\ScheduledTaskLogRepository
        arguments: ['@Doctrine\Common\Persistence\ManagerRegistry']