language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files
        - .phpunit

env:
    - SYMFONY_VERSION=3.3.*

matrix:
    include:
        - php: 7.0
          env: SYMFONY_VERSION=3.3.*@dev
        - php: 7.0
          env: SYMFONY_VERSION=3.4.*@dev
        - php: 7.1
          env: SYMFONY_VERSION=4.0.*@dev
        - php: 7.2
          env: SYMFONY_VERSION=4.0.*@dev

before_install:
    - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - composer self-update
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install: composer update --prefer-source $COMPOSER_FLAGS

script:
    - ./vendor/bin/simple-phpunit